### ISSUE TITLE
Can importlib_metadata dependency be removed?

### ISSUE THREAD

**Issue by akrherz** [conda-forge/streamlit-feedstock#110]
### Comment:

Does this feedstock recipe need the `importlib_metadata` dependency anymore given streamlit/streamlit#8094 ?

**Comment by kmcgrady** [comment]
Hey @akrherz Thanks for the issue. We did have some issues building in the past due to missing imports for some reason. For our next release, I'll do a check to see if removal is possible. It may be needed but not as an official dependency but one for building the package itself.

**Comment by kmcgrady** [comment]
Successfully removed for 1.41.0
