### ISSUE TITLE
streamlit conda package isn't updated to 0.82

### ISSUE THREAD

**Issue by igozali** [conda-forge/streamlit-feedstock#21]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Streamlit released a new version 0.82.0 21 days ago [here](https://github.com/streamlit/streamlit/releases/tag/0.82.0) but the package on `conda-forge` hasn't been updated?

**Comment by igozali** [comment]
Here's the link to the streamlit conda-forge package: https://anaconda.org/conda-forge/streamlit

Maybe cc @kmcgrady?

**Comment by kmcgrady** [comment]
Hey @igozali I was able to fix it. I think 0.82.0 is out. Let me know if you continue seeing issues.
