### ISSUE TITLE
cannot install streamlit via conda due to package conflict

### ISSUE THREAD

**Issue by sleepybunn** [conda-forge/streamlit-feedstock#30]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

hello,

i've problem in installing streamlit v0.86.0 via conda, the solving environment took long time, and failed, after that error found conflict

but the package report is confusing

i used :

conda install -c conda-forge streamlit=0.86.0

after that, i tried :

conda install -c conda-forge streamlit

after that it can install streamlit, but the version is v0.81.1

could anyone help to locate the conflict?

i've just re-installed the miniconda, i deleted all packages, and after that installed spyder, pandas, plotly, altair only, before trying to install streamlit
[package_list.txt](https://github.com/conda-forge/streamlit-feedstock/files/6965708/package_list.txt)
![conda_info](https://user-images.githubusercontent.com/75115235/128966066-e0f05320-e658-4c67-a2aa-b7ab173cb3b8.png)

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by sleepybunn** [comment]
i added update to this case, i tried to install via pip

pip3 install streamlit

it can install streamlit v0.86.0, i've tested it, and seems working fine

i think the issue could be on conda

**Comment by kmcgrady** [comment]
Thank you for this issue. Going to close because it seems like things work and this is on a much older version of Streamlit.
